// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKgPTDoyYL5S2DBjagWIgeNxoxIaBNzck',
    appId: '1:677587312096:web:51b47c0c292623e75adf85',
    messagingSenderId: '677587312096',
    projectId: 'ecommerceappcompleteuiproject',
    authDomain: 'ecommerceappcompleteuiproject.firebaseapp.com',
    storageBucket: 'ecommerceappcompleteuiproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_UwDI7gAmQgP7fgJOAJopPKLDo7uJohU',
    appId: '1:677587312096:android:ecc911dd652070825adf85',
    messagingSenderId: '677587312096',
    projectId: 'ecommerceappcompleteuiproject',
    storageBucket: 'ecommerceappcompleteuiproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpMrw2X02CnAKZ4wl4oQrQUR3SxIzrehQ',
    appId: '1:677587312096:ios:e50718ba252368895adf85',
    messagingSenderId: '677587312096',
    projectId: 'ecommerceappcompleteuiproject',
    storageBucket: 'ecommerceappcompleteuiproject.appspot.com',
    iosBundleId: 'com.example.ecommerceAppCompleteUiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpMrw2X02CnAKZ4wl4oQrQUR3SxIzrehQ',
    appId: '1:677587312096:ios:0eb7114e484db63d5adf85',
    messagingSenderId: '677587312096',
    projectId: 'ecommerceappcompleteuiproject',
    storageBucket: 'ecommerceappcompleteuiproject.appspot.com',
    iosBundleId: 'com.example.ecommerceAppCompleteUiProject.RunnerTests',
  );
}
